### ISSUE TITLE
DICE reference set usage with SingleR

### ISSUE THREAD

**Issue by ppaxisa** [LTLA/celldex#10]
Hi Aaron, 

Thank you for putting together these collections of datasets. I'm not sure whether this issue belongs to SingleR or celldex. I want to use the `celldex::DatabaseImmuneCellExpressionData()` with SingleR, with the manual stating: 

> TPM normalized values for each cell type were downloaded from https://dice-database.org/ downloads. 

The [DICE](https://dice-database.org/downloads) website states that:

> These files contain RNA expression data for each cell type reported as transcripts per million (TPM). Each row contains the expression value for the gene indicated in column A, and starting in column D are individual replicates from different donors. Replicates from the same donor are not necessarily in the same column.

The way I understand this (and tested in other contexts) is that the rows (genes) are shuffled across donor for each cell type gene expression matrix. So that each column is not really reflecting a sample. Does that matter for the performance of SingleR, or is it going to average expression for a given gene / cell type combination anyway?

Thanks,
Pierre-Paul

**Comment by LTLA** [comment]
> So that each column is not really reflecting a sample

That would also be my conclusion.

> Does that matter for the performance of SingleR, or is it going to average expression for a given gene / cell type combination anyway?

It will affect the result, compared to what we might have gotten fromcolumns that actually correspond to replicate samples. But It is harder to say whether it makes the result better or worse. I would speculate that it makes the predictions a bit worse, because **SingleR** is not being presented with the full variability across samples (given that they're effectively averaged within each column by mixing with other samples). As a result, **SingleR** may give weaker-than-expected scores to test samples that are more variable than the averaged training data suggests. Also, if you were to use the other `de.method=` choices, **SingleR** would not be able to penalize highly variable marker genes, so it might choose markers that are not so good.

At this point, there's not much that can be done, so best to just cross your fingers and hope for the best. I don't think there is a critical problem with using the DICE data with **SingleR**, so you might as well give it a shot.

**Comment by ppaxisa** [comment]
Hi Aaron,

Thanks for the help, I did run SingleR with Monaco and DICE reference and they gave consistent cell type assignments so it's working ok!
