### ISSUE TITLE
Error in `req_perform()`, Error in save_file, databases cannot be loaded

### ISSUE THREAD

**Issue by mdozmorov** [LTLA/celldex#28]
I'm getting various errors when trying loading the databases. Played with setting `cache`, didn't help. Looking through other issues, still don't have a solution. Is there something obvious I'm missing?
```{r}
> se <- fetchReference("immgen", "2024-02-26", realize.assays = TRUE, overwrite=TRUE)
Error in `req_perform()`:
! Failed to parse error body with method defined in `req_error()`.
Caused by error in `resp_body_json()`:
! Unexpected content type "text/html".
• Expecting type "application/json" or suffix "json".
Run `rlang::last_trace()` to see where the error occurred.
> se <- fetchReference("hpca", "2024-02-26")
Error in save_file(path = paste(project, asset, version, x, sep = "/"),  : 
  failed to save 'celldex/hpca/2024-02-26/assays/0/OBJECT'; Failed to parse error body with method defined in `req_error()`.
```

**Comment by LTLA** [comment]
No idea; both functions work fine for me. Also, the API does not return HTML error responses, it should be JSON-only.

My guess is that your errors are actually being generated from some proxy or firewall between you and the Cloudflare network, as these often generate HTML errors. I also had to ask for an exception in the proxy at work because the artifactdb.com domain was previously associated with some gambling website before I bought it.

In any case, the latest version of the **gypsum** package on `master` attempts to report any non-JSON error as-is, so it should be easier to see what the real problem is.

**Comment by mdozmorov** [comment]
I should've thought of this, our new VPN, Zscaler, is indeed a problem. Switching it off solves it. Thanks, Aaron!
